import type { Metadata } from 'next';
import { Geist_Mono, Lexend_Deca } from 'next/font/google';
import './globals.css';
import { MainContainer } from '@/components/main-container';

const geistSans = Lexend_Deca({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <MainContainer className='inline'>
          {children}
        </MainContainer>
      </body>
    </html>
  );
}
